---
# Check if the system is supported as configured for Login Enterprise installation
- block:
  - name: RAM Check
    assert:
      that:
        - ansible_memtotal_mb >= 4096
  - name: CPU Check
    assert:
      that:
        - ansible_processor_cores >= 2
  - name: Disk Check
    # 30 GB
    assert:
      that:
        - (ansible_mounts|selectattr("mount", "equalto", "/")|list)[0].size_available >= 32212254720
