---
- name: Ensure local admin account
  user:
    name: "{{ admin_username }}"
    password: "{{ admin_password | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create
  when: not appliance_installed.stat.exists