---
# tasks file for lvsi_appliance_base
# everything outside first run and any post first run tasks

# base packages
# admin account
# admin account in sudoers
# loginenterprise group
# sysctl

# tarball
# extract tarball
# motd

- block:
    - name: Check if appliance is already installed
      stat:
        path: "{{ install_dir }}"
      register: appliance_installed

- block:
    - name: Check prereqs
      stat:
        path: "{{ temp_dir }}/le-appliance/prereqs.sh"
      register: prereqs_installed

    - name: Ensure local admin account
      user:
        name: "{{ admin_username }}"
        password: "{{ admin_password | password_hash('sha512') }}"
        shell: /bin/bash
        update_password: on_create
        createhome: yes
        group: admin

    - name: Ensure local admin account is in sudoers
      lineinfile:
        path: /etc/sudoers
        line: "{{ admin_username }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Ensure local loginenterprise group
      group:
        name: loginenterprise
        state: present
        guid: 1002
  when: not appliance_installed.stat.exists